name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        cargo build --release

    - name: Install rsync and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard resolvconf rsync sshpass

    - name: Set up WireGuard VPN
      env:
        WG_CONFIG: ${{ secrets.WG_CONFIG }}
      run: |
        echo "$WG_CONFIG" | sudo tee /etc/wireguard/wg0.conf
        sudo wg-quick up wg0
        sudo wg show

    - name: Rsync binary to remote server with SSH password
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" ./target/release/timecard ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

    - name: Tear down VPN connection
      if: always()
      run: |
        sudo wg-quick down wg0